### ISSUE TITLE
TCGA Data loading doesn't seem to work

### ISSUE THREAD

**Issue by AndyBlake** [akoch8/mexpress#1]
l think the urls that you are trying to load through your bash scripts don't work anymore? I could be wrong though.

**Comment by akoch8** [comment]
You are correct Andy, the URLs no longer work. The original TCGA data repository has been moved to the GDC portal ([https://portal.gdc.cancer.gov/](https://portal.gdc.cancer.gov/)). I plan to update MEXPRESS so that it uses the GDC portal instead of the now deprecated TCGA portal.
